### PR TITLE
Fixes as per comment in issue #49

### LINKED ISSUE #49: Multiple tests failling
https://travis-ci.org/logstash-plugins/logstash-output-redis/builds/236452094

```
  1) LogStash::Outputs::Redis Redis#receive in batch mode should call buffer_receive
     Failure/Error: expect{redis.receive(event)}.to_not raise_error
     
       expected no Exception, got #<RSpec::Mocks::MockExpectationError: (<LogStash::Outputs::Redis key=>"thekey", data_type=>"list", ba...timestamp\":\"2017-05-27T04:20:40.423Z\",\"@version\":\"1\",\"message\":\"test\"}"], "thekey", nil)> with backtrace:
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/stud-0.0.22/lib/stud/buffer.rb:221:in `block in buffer_flush'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'
         # ./lib/logstash/outputs/redis.rb:236:in `send_to_redis'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-codec-json-3.0.2/lib/logstash/codecs/json.rb:42:in `encode'
         # ./lib/logstash/outputs/redis.rb:150:in `receive'
         # ./spec/unit/outputs/redis_spec.rb:35:in `block in /home/travis/build/logstash-plugins/logstash-output-redis/spec/unit/outputs/redis_spec.rb'
         # ./spec/unit/outputs/redis_spec.rb:35:in `block in /home/travis/build/logstash-plugins/logstash-output-redis/spec/unit/outputs/redis_spec.rb'
         # ./spec/unit/outputs/redis_spec.rb:34:in `block in (root)'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
     # ./spec/unit/outputs/redis_spec.rb:35:in `block in /home/travis/build/logstash-plugins/logstash-output-redis/spec/unit/outputs/redis_spec.rb'
     # ./spec/unit/outputs/redis_spec.rb:34:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/w
```
```
  1) LogStash::Outputs::Redis Redis#receive in batch mode should call buffer_receive
     Failure/Error: expect(redis).to receive(:buffer_receive).exactly(10000).times.and_call_original
     
       (<LogStash::Outputs::Redis key=>"thekey", data_type=>"list", batch=>true, batch_events=>50, id=>"redis_c5ebd5ad-51da-4633-8c5d-68756bd28aa8", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_0c16f495-39b0-45d4-97ec-ec2d1a0d8aba", enable_metric=>true, charset=>"UTF-8">, workers=>1, name=>"default", host=>["127.0.0.1"], shuffle_hosts=>true, port=>6379, db=>0, timeout=>5, batch_timeout=>5, reconnect_interval=>1, congestion_threshold=>0, congestion_interval=>1>).buffer_receive(*(any args))
           expected: 10000 times with any arguments
           received: 9999 times with any arguments
     # ./spec/unit/outputs/redis_spec.rb:28:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 6.82 seconds (files took 2.93 seconds to load)
```

### PR DESCRIPTION
**Pull request by guyboertje**
Fixes #49

### CODE REVIEW

File: spec/unit/outputs/redis_spec.rb [hunk 1]
```diff
@@ -11,14 +11,13 @@
...
     let(:key) { "thekey" }
-    let(:payload) { "somepayload"}
-    let(:event) { LogStash::Event.new({"message" => "test"}) }
     let(:config) {
       {
         "key" => key,
         "data_type" => "list",
         "batch" => true,
         "batch_events" => 50,
+        "batch_timeout" => 3600 * 24,
```
Comment (colinsurprenant) [inline spec/unit/outputs/redis_spec.rb]: I suggest we add a comment here to explain this setting...

Comment (guyboertje) [inline spec/unit/outputs/redis_spec.rb]: OK

**Comment by colinsurprenant** [comment]
LGTM
